### ISSUE TITLE
Video uploads tracker issue

### ISSUE THREAD

**Issue by miguelraz** [JuliaCon/JuliaCon.jl#17]
This is a tracker issue related to uploading the submitted video files appropriately to youtube. This is work is helped by @aviks and sponsored by NumFocus

----
### JuliaCon2021 video uploading specifications: 
- [ ]  Every video must have the JuliaConIntro animation appended to the beginning of the video. 
    - This animation is available on the S3 bucket as `station ident`.
    - There are 269 uploaded objects so far.
- [ ]  Every video must be published at the appropriate time, and uploaded before that. Ideally, a week before the conference for QA and feedback. This is July 21st, 2021 as the latest.
  - YT only permits 15min intervals, the floor of the talk interval's time rounded to the nearest quarter of a hour will be taken.
      - **Example**: If the talk is schedule for 12:40, An upload is fine if it is set at 12:30.
  - [ ]  Times can be uploaded as the `snippet.publishedAt` field in the request header with the ISO 8601 format.
      - API is [found here](        https://developers.google.com/youtube/v3/docs/videos?hl=en), format is *YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)*
    - Timezones can be designated as UTC with Z at the end.
    * [**Example**](https://www.lexjansen.com/nesug/nesug06/cc/cc17.pdf):
                  1994-11-05T08:15:30-05:00 corresponds to November 5, 1994, 8:15:30 am, US Eastern Standard Time.
                  1994-11-05T13:15:30Z corresponds to the same instant.
      - [ ] REQUIRES TEST UPLOADS
- [ ] Every video must be able to be viewed as a planned broadcast so that users can subscribe/set reminders. It is sufficient to set the publishing time appropriately for this to be true.
- [ ] Every video must have:
   - Title matching the corresponding JuliaCon2021 entry
       - Title format is `"Talk Title | Speaker Name | Juliacon 2021"`. Should the title be too large for the title character limit, the talk title should be replaced with `...` appropriately. 
   - Description matching the abstract of the JuliaCon2021 entry
   - status.PrivacyStatus set as "scheduled"
- [ ] Every video must have the corresponding thumbnail of its JuliaCon2021 entry
   - Every thumbnail must be produced according to the given template, and every thumbnail is unique
   - There may be a variety of different pixel sizes that can be uploaded - We'll stick to the default.
- [ ] Every video must, to the extent possible, minimize ambient noise like fans, whirring, etc. 
    - [ ] Test Elrod BLAS linear algebra upload contains fan noise. Noise gating that seems appropriate.
- [ ] There must be no duplicate uploads
    - [ ]  Test: Dagger.jl upload
- [ ]  Every video must be uploaded to the "8th annual JuliaCon 2021" youtube playlist.

-----

### Additional requirements
- [ ] Late submissions, scheduling changes, bug fixes, and last minute edits are unavoidable. The person in charge of this video uploading pipeline must be available prior to and throughout the duration of the event.
- [ ] A "Welcome to JuliaCon" video tutorial showcasing the REPL interface, website, and Discord facilities + CoC would be welcome.

----

### Workflow 
- Download the videos with [the aws-cli](https://github.com/aws/aws-cli) from the S3 bucket. (~50GB)
- Generate the appropriate thumnbnails [code forthcoming].
- Process the files with `ffmpeg` to remove background noise where possible.
- Upload the files by using the YouTube API with the JuliaLang Youtube API Credentials.
